### ISSUE TITLE
'babel-node' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by tatchi** [danielstern/advanced-redux#2]
Hello,

I just started the tutorial and checked out the "immutability-start" branch. I followed the instructions to install the required dependencies (also installed the global ones).

I got an error while trying to start the application (npm start command):

`
'babel-node' is not recognized as an internal or external command,`

If figured out that I had to install the babel-cli package:

`npm install -g babel-cli`

I don't know exactly which version should be installed, but seems like the latest one is fine.

For information, I'm running on a window 10 machine with node 7.2 and npm 3.10.9.

Btw, many thanks for the great video :)

**Comment by lalwanivikas** [comment]
Can confirm. Happens same on Mac as well. 

Error is `babel-node: command not found`.

And @tatchi's solution works fine!

**Comment by danielstern** [comment]
Hey @tatchi!

Thanks for pointing out the error, and for the great fix!

I've added a message to the course discussion page with your fix, so hopefully it should steer people in the right direction

**Comment by harshan89** [comment]
It worked for me after install, **npm install -g babel-cli**

**Comment by mrp100461** [comment]
Daniel why dont you  help the people on the course work on the discussion tab of the plural sight there are a lot off people who have problems and  no help!!!!!
