### ISSUE TITLE
webpack2 ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [danielstern/advanced-redux#4]
webpack2 ?

**Comment by buvinghausen** [comment]
Considering [webpack3](https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b) is out I'd rephrase the question.

Personally start with [react-slingshot](https://github.com/coryhouse/react-slingshot) then layer in the added packages needed in this class...

**Comment by xgqfrms-GitHub** [comment]
# OK!
