### ISSUE TITLE
Avoid install global dependencies

### ISSUE THREAD

**Issue by jfcorugedo** [danielstern/advanced-redux#6]
Hi!

First of all I'd like to thank you for this course. It's one of the best I've seen in a long time, keep up the good work!

Just to say something to be improved, instead of installing a lot of global dependencies it's better, in my humble opinion, to add those dependencies to dev scope.

Just add these dependencies to the package.json:

```
"devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-core": "^6.18.2",
    "babel-loader": "^6.2.8",
    "babel-plugin-transform-object-rest-spread": "^6.19.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.23.0",
    "babel-regenerator-runtime": "^6.5.0",
    "nodemon": "^1.11.0",
    "webpack": "^1.13.3",
    "webpack-dev-middleware": "^1.10.1",
    "webpack-dev-server": "^1.16.2",
    "webpack-hot-middleware": "^2.17.1"
  },
```

And now npm start works without any global dependency installed

**Comment by ahmad2smile** [comment]
Just install all the dependencies give in README for global as local dev deps... and then install babel-cli and replace this line in package.json

`"dev": "nodemon --watch server/**/* --exec babel --inspect server/server.js"`

**Comment by danielstern** [comment]
@jfcorugedo I'm keeping these as global installs because some operating systems don't read the CLI commands from local folders very well
