### ISSUE TITLE
package.json is missing babel-cli

### ISSUE THREAD

**Issue by dekmetzi** [danielstern/advanced-redux#8]
`> redux-messenger@1.0.0 start /path/to/advanced-redux
> babel-node server/server.js

sh: babel-node: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! redux-messenger@1.0.0 start: `babel-node server/server.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the redux-messenger@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

Project worked after adding: 
`"devDependencies": {
    "babel-cli": "^6.0.0",
`

**Comment by mahendranepali** [comment]
do a npm list babel-node
if it returns empty
then try npm install -g babel-cli  . 
it worked for me

**Comment by danielstern** [comment]
Package now has `babel-cli`

**Comment by erikiva** [comment]
It's not added on the branch that first tries to do npm install : immutability-start
