### ISSUE TITLE
branch immutability-start not installing and running

### ISSUE THREAD

**Issue by Puspendert** [danielstern/advanced-redux#9]
after following the steps from cloning the project to installing the dependency, I am unable to start the application. The error logs.

> **Puspenders-MacBook-Pro:visual-studio puspender$** git clone https://github.com/danielstern/advanced-redux.git
> Cloning into 'advanced-redux'...
> remote: Enumerating objects: 351, done.
> remote: Total 351 (delta 0), reused 0 (delta 0), pack-reused 351
> Receiving objects: 100% (351/351), 50.39 KiB | 55.00 KiB/s, done.
> Resolving deltas: 100% (162/162), done.
> Puspenders-MacBook-Pro:visual-studio puspender$ cd re
> react-basic-authentication-example/ react-redux-weather/
> react-redux-blog-route/ reddice-master/
> react-redux-registration-login-example/
> 
> **Puspenders-MacBook-Pro:visual-studio puspender$** cd advanced-redux
> **Puspenders-MacBook-Pro:advanced-redux puspender$** git checkout immutability-start
> Branch 'immutability-start' set up to track remote branch 'immutability-start' from 'origin'.
> Switched to a new branch 'immutability-start'
> 
> **Puspenders-MacBook-Pro:advanced-redux puspender$** npm install
> npm WARN deprecated babel-preset-es2015@6.24.1: 🙌 Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
> 
> > fsevents@1.2.4 install /Work/IDEs workspace/visual-studio/advanced-redux/node_modules/fsevents
> > node install
> 
> [fsevents] Success: "/Work/IDEs workspace/visual-studio/advanced-redux/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
> Pass --update-binary to reinstall or --build-from-source to recompile
> 
> > nodemon@1.18.9 postinstall /Work/IDEs workspace/visual-studio/advanced-redux/node_modules/nodemon
> > node bin/postinstall || exit 0
> 
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN redux-messenger@1.0.0 No repository field.
> 
> added 629 packages from 476 contributors and audited 5713 packages in 30.603s
> found 2 vulnerabilities (1 high, 1 critical)
> run `npm audit fix` to fix them, or `npm audit` for details
> 
> **Puspenders-MacBook-Pro:advanced-redux puspender$** npm install -g babel-loader@6.2.8 babel-plugin-transform-object-rest-spread@6.19.0 babel-preset-es2015@6.18.0 babel-preset-react@6.23.0 babel-regenerator-runtime@6.5.0 nodemon@1.11.0 webpack@1.13.3 webpack-dev-server@1.16.2 webpack-hot-middleware@2.17.1 webpack-dev-middleware@1.10.1
> npm WARN deprecated babel-preset-es2015@6.18.0: 🙌 Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
> /usr/local/bin/nodemon -> /usr/local/lib/node_modules/nodemon/bin/nodemon.js
> /usr/local/bin/webpack -> /usr/local/lib/node_modules/webpack/bin/webpack.js
> /usr/local/bin/webpack-dev-server -> /usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js
> npm WARN babel-loader@6.2.8 requires a peer of babel-core@^6.0.0 but none is installed. You must install peerdependencies yourself.
> 
> + babel-preset-react@6.23.0
> + babel-regenerator-runtime@6.5.0
> + babel-plugin-transform-object-rest-spread@6.19.0
> + webpack-hot-middleware@2.17.1
> + webpack-dev-middleware@1.10.1
> + babel-loader@6.2.8
> + babel-preset-es2015@6.18.0
> + nodemon@1.11.0
> + webpack-dev-server@1.16.2
> + webpack@1.13.3
> updated 10 packages in 23.341s
> 
> **Puspenders-MacBook-Pro:advanced-redux puspender$** npm start
> 
> > redux-messenger@1.0.0 start /Work/IDEs workspace/visual-studio/advanced-redux
> > babel-node server/server.js
> 
> sh: babel-node: command not found
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! redux-messenger@1.0.0 start: `babel-node server/server.js`
> npm ERR! spawn ENOENT
> npm ERR!
> npm ERR! Failed at the redux-messenger@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /Users/puspender/.npm/_logs/2019-01-12T18_18_30_721Z-debug.log

**Comment by danielstern** [comment]
Try `npm install --save-dev babel-node`
